server:
  port: 8001
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/adminDB
jwt:
  header: Authorization
  secret: schoolPortal
  expiration: 900000
  route:
    authentication:
      path: /auth
      refresh: /refresh
eureka: 
  client:  
    service-url: 
      default-zone:  http://localhost:8777/eureka